# Generated by Django 6.0.2 on 2026-05-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='priority_bonus',
            field=models.FloatField(default=0.0),
        ),
    ]
